# Input modality specification
DATASET:
  - S2
  - BD

IN_SHAPE:
  S2: [128, 128, 10]
  BD: [128, 128, 1]

# Training configuration
N_CLASSES: 3
LR: 0.0001
FT_LR: 0.01 # Fine-tuning learning rate
BATCH_SIZE: 4
N_EPOCHS: 150
FT_EPOCHS: 30 # Fine-tuning epochs
MONITOR: val_loss
MODE: min
PATIENCE: 10

# Inference configuration
STRIDE_RATIO: 0.5

# Paths
DATA_PATH: ./data/processed/
CHECKPOINT_PATH: ./checkpoint/
LOG_PATH: ./log/
PREDICTION_PATH: ./output/
AOI_PATH: ./data/raw/aoi/
